
name: 'vilnius_pub'
version: '1.0.0'
config-version: 2

profile: 'vilnius_pub'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
