vilnius_pub:
  outputs:
    dev:
      type: duckdb
      path: ./vilnius_pub.duckdb
      threads: 5
      attach:
        - path: "../untappd_checkins.duckdb"
          alias: untappd
  target: dev
