---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    name: Format and style checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: sbt scalafmtCheck
      - run: sbt scalafmtSbtCheck
      - run: sbt "scalafix --check"
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v0.0.2
        with:
          file_or_dir: .github/workflows/ci.yml gcloud/cloudbuild-master.yaml

  test:
    name: Compile and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11
      - run: sbt build
