name: Build and deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v3
    - uses: opt-nc/setup-duckdb-action@v1.1.3
    - uses: oven-sh/setup-bun@v2
    - uses: astral-sh/setup-uv@v6

    - name: 'Import to DuckDB'
      run: just csv-to-duckdb

    - name: 'Clean and transform data'
      run: just transform

    - name: 'Install dashboard'
      run: just dashboard-install

    - name: 'Build dashboard'
      run: just dashboard-build

    - uses: actions/upload-pages-artifact@v3
      with:
        path: 'dashboard/build'
    - uses: actions/deploy-pages@v4
