name: Import data from BigQuery to CSV

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'

    steps:
    - uses: 'actions/checkout@v4'
    - uses: extractions/setup-just@v3
    - uses: opt-nc/setup-duckdb-action@v1.1.3

    # DuckDB BigQuery extension does not support WIF. Therefore we need to
    # use service account key here.
    - uses: 'google-github-actions/auth@v3'
      with:
        credentials_json: "${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}"

    - name: 'From BigQuery to DuckDB'
      run: just bq-to-duckdb

    - name: 'From DuckDB to CSV'
      run: just duckdb-to-csv

    - uses: stefanzweifel/git-auto-commit-action@v6
